### ISSUE TITLE
v1.1 Roadmap / Ideas

### ISSUE THREAD

**Issue by klange** [kuroko-lang/kuroko#2]
This ticket is for tracking ideas for the next full release of Kuroko.

1.0 was essentially a demo, the first version of Kuroko as a viable language built from the core of _Crafting Interpreters_. 1.1 is intended to be a "real" release - one with a production-ready release process, "complete" standard library, and stable ABI/API for extension developers and embedders.

- [ ] Standard library improvements:
    - [ ] `subprocess` module, etc. (can we do this in managed code around the `os` module?)
    - [x] Complete `os` coverage (what's still missing that we need? We have the exec family, fork, ...)
    - [x] `socket` module
        - [ ] useful extensions (`http.server`; `requests` implementation?)
    - [x] Merge harjit's `codecs` implementation
    - [x] Pull object methods out of `vm.c` and use macros from bim development branch. 
    - [x] `str` methods:  `replace`, `startswith`, `endswith`, `find`/`index`
    - [x] `isalpha` (etc.); support other sequences in `join`
    - [x] Mutable sequence methods: `index`, `count`, `clear`, `copy`, `remove`, `reverse`
    - [x] `del` on slices
    - [x] Mapping methods: `clear`,`copy`,`get`,`setdefault`,`update`
    - [x] Pull `set` into C core
- [x] Add class decorators (bim syntax files would really like to have this)
- [x] Threading? ~~Or maybe that's best left way on the backlog for "2.0".~~ _I actually sat down and did this, though it's still missing locks in a lot of places and is only known to work on Linux..._
- [x] Persist module bytecode with a marshaling format. Bytecode itself can be directly saved; function constants tables are a bit trickier. Format stability is not important, but we should be able to write once and then read from future runs of the same interpreter version like Python does with 'pyc' files. _This is experimental, but a functional demonstration is provided in 1.1_
- [ ] Finish the documentation rewrite (https://kuroko-lang.github.io/docs.html)
    - [x] Add docstring bindings for everything in the standard library. (`__builtins__` still needs full coverage of types)
    - [x] Build tools for turning docstring docs into usable HTML documentation, like Sphinx does.
    - [x] Complete C API documentation, follow a standard like Doxygen, add build tools for it.
    - [ ] Prose docs for embedding and extending, building from source, something like the _Python Tutorial_.
- [ ] Rewrite/reorganize headers:
    - [ ] C library users should only need to include `<kuroko/kuroko.h>` and not separate headers.
    - [x] Library sources should also be including things like `<kuroko/kuroko.h>` instead of `"kuroko.h"`
    - ~~Need a "config.h" to hold build-time settings like whether threads are enabled, as they affect struct definitions.~~ This is still a problem, but not as much as it was...
- [ ] Add an autotools-like `configure` script so we can stop worrying about weirdness when building for win32? Maybe also integrate some of the WASM build scripts into that...
- [x] Make class fields work like in Python / eliminate the "fields"/"methods" split?
- [x] Implement ~~multiple inheritance~~, runtime attribute lookup ordering? _Not doing multiple inheritance now or ever, but maybe mixins will show up at some point._
- [x] Type hinting annotations
   - [x] On module-level `let` declarations
   - [x] In function signatures
   - [x] On class attributes 

## Deferred to 1.2
- Rewrite the compiler to build an AST so we can reasonably implement things like ~~multiple assignment, real tuple syntax~~, etc.
- Clean up cruft from _Crafting Interpreters_ that no longer makes sense in modern Kuroko: 
    - Merge "chunks" and "functions" as there is a 1:1 relationship between the two.
    - ~~Call the result "code objects" like Python does?~~ _**Done!**_
    - ~~"Functions" vs "Closures" makes little sense in the C API.~~ _Partially done_
    - Fix all those `IS_TYPE` / `AS_TYPE` macros to use the format from `util.h` with actual type names.
    - Eliminate `object.c` and move things into their `obj_` sources (and all the common stuff into `memory.c`? which should probably be renamed `gc.c`?)

## Cancelled
- ~~Write an `ARCHITECTURE.md` with a prose description of how everything meshes together.~~  We have a website, with extensive documentation, it describes the architecture of the compiler.
- ~~Make the compiler fully re-entrant. There were speed concerns with making the VM re-entrant as means of supporting threading, but this is not the case with the compiler, so we can definitely have a top-level state we chain down to everything...~~ A complete compiler rewrite with an AST is planned for 1.2, so I'm not going to waste my time with this right now.
- ~~Consider whether basic value types should be nixed and moved to objects. Even Python has its integers and such as objects, and it would allow us to reduce stack references to just pointers, halving (or more) their size. Having a single path for type checking might also improve performance.~~ _**Followup:** This was tried and it improved some cases and destroyed some others. Not really sure if it's worthwhile unless we want everything to have fields, like in Python._
