### ISSUE TITLE
Kuroko 1.6 Roadmap

### ISSUE THREAD

**Issue by klange** [kuroko-lang/kuroko#39]
- [ ] Nested destructuring in `for` loop assignment lists
- [ ] Arbitrary assignment targets in `for` loops
    - Eg. object members
- [ ] Some sort of syntax for _not_ implicitly declaring names in various block statements?
    - Includes `for`, `with ... as ...`, `def`.
- [x] Ordered dicts by default?
- [ ] Bare `raise`
